<?php
return [
	'key' => 'general_settings',
	'title' => __( 'Special Settings', 'artist' ),
	'fields' => [
		[
			'key' => 'general_settings',
			'label' => __( 'General settings', 'artist' ),
			'name' => 'general_settings',
			'type' => 'tab',
		],
		[
			'key' => 'contact_number',
			'label' => __( 'Contact Number', 'artist' ),
			'instructions' => __( 'For Special Words you can enter your text into [] brackets', 'artist' ),
			'name' => 'contact_number',
			'type' => 'text',
		],
		[
			'key' => 'copyright_text',
			'label' => __( 'CopyRight Text', 'artist' ),
			'instructions' => __( 'For Special Words you can enter your text into [] brackets', 'artist' ),
			'name' => 'copyright_text',
			'type' => 'text',
		],
		[
			'key' => 'home_tab',
			'label' => __( 'Home', 'artist' ),
			'name' => 'home_tab',
			'type' => 'tab',
		],
		[
			'key' => 'home_into_main_text',
			'label' => __( 'Intro Main Text', 'artist' ),
//			'instructions' => __( 'For Special Words you can enter your text into [] brackets', 'artist' ),
			'name' => 'home_into_main_text',
			'type' => 'text',
		],
		[
			'key' => 'home_into_sec_text',
			'label' => __( 'Intro Second Text', 'artist' ),
//			'instructions' => __( 'For Special Words you can enter your text into [] brackets', 'artist' ),
			'name' => 'home_into_sec_text',
			'type' => 'text',
		],
		[
			'key' => 'home_intro_discover_link',
			'label' => __( 'Intro Discover Button Link', 'artist' ),
			'name' => 'home_intro_discover_link',
			'default_value' => '#hello',
			'type' => 'url',
		],
		[
			'key' => 'social_media',
			'label' => __( 'Social Media', 'artist' ),
			'name' => 'social_media',
			'type' => 'tab',
		],
		[
			'key' => 'social_media_facebook',
			'label' => __( 'Facebook Url', 'artist' ),
			'name' => 'social_media_facebook',
			'default_value' => 'http://facebook.com/',
			'type' => 'url',
		],
		[
			'key' => 'social_media_twitter',
			'label' => __( 'Twitter Url', 'artist' ),
			'name' => 'social_media_twitter',
			'default_value' => 'http://twitter.com/',
			'type' => 'url',
		],
		[
			'key' => 'social_media_instagram',
			'label' => __( 'Instagram Url', 'artist' ),
			'name' => 'social_media_instagram',
			'default_value' => 'http://instagram.com/',
			'type' => 'url',
		],
		[
			'key' => 'blog_settings',
			'label' => __( 'Blog', 'artist' ),
			'name' => 'blog_settings',
			'type' => 'tab',
		],
		[
			'key' => 'blog_posts_per_page',
			'label' => __( 'Posts Per Page', 'artist' ),
			'name' => 'blog_posts_per_page',
			'type' => 'number',
		],
		[
			'key' => 'shop_settings',
			'label' => __( 'Shop', 'artist' ),
			'name' => 'shop_settings',
			'type' => 'tab',
		],
		[
			'key' => 'shop_posts_per_page',
			'label' => __( 'Products Per Page', 'artist' ),
			'name' => 'shop_posts_per_page',
			'type' => 'number',
		],
		[
			'key' => 'exclude_product_categories',
			'label' => __( 'Show categories except these', 'artist' ),
			'name' => 'exclude_product_categories',
			'type' => 'taxonomy',
			'taxonomy' => 'product_cat',
		],
		[
			'key' => 'aparat_tab',
			'label' => __( 'Aparat', 'artist' ),
			'name' => 'aparat_tab',
			'type' => 'tab',
		],
		[
			'key' => 'aparat_id',
			'label' => __( 'Aparat Page ID', 'artist' ),
			'name' => 'aparat_id',
			'default_value' => 'artist',
			'type' => 'text',
		],
		[
			'key' => 'aparat_title',
			'label' => __( 'Section Title', 'artist' ),
			'name' => 'aparat_title',
			'type' => 'text',
			'default_value' => 'آپارات'
		],
		[
			'key' => 'aparat_subtitle',
			'label' => __( 'Section SubTitle', 'artist' ),
			'name' => 'aparat_subtitle',
			'type' => 'text',
			'default_value' => 'هر آنچه که در خانواده اسنوا اتفاق می‌افتد'
		],
		[
			'key' => 'aparat_button_text',
			'label' => __( 'Button Text', 'artist' ),
			'name' => 'aparat_button_text',
			'type' => 'text',
			'default_value' => 'مشاهده کانال اسنوا در آپارات'
		],
		[
			'key' => 'instagram_tab',
			'label' => __( 'Instagram', 'artist' ),
			'name' => 'instagram_tab',
			'type' => 'tab',
		],
		[
			'key' => 'instagram_id',
			'label' => __( 'Instagram Page ID', 'artist' ),
			'name' => 'instagram_id',
			'default_value' => 'artist',
			'type' => 'text',
		],
		[
			'key' => 'instagram_access_token',
			'label' => __( 'Instagram Access Token', 'artist' ),
			'name' => 'instagram_access_token',
			'default_value' => '',
			'type' => 'text',
		],
		[
			'key' => 'instagram_title',
			'label' => __( 'Section Title', 'artist' ),
			'name' => 'instagram_title',
			'type' => 'text',
			'default_value' => 'با هشتگ [#SNOWA]'
		],
		[
			'key' => 'instagram_subtitle',
			'label' => __( 'Section SubTitle', 'artist' ),
			'name' => 'instagram_subtitle',
			'type' => 'textarea',
			'default_value' => 'عکس‌های خود را به اشتراک بگذارید…'
		],
		[
			'key' => 'instagram_button_text',
			'label' => __( 'Button Text', 'artist' ),
			'name' => 'instagram_button_text',
			'type' => 'text',
			'default_value' => 'مشاهده در اینستاگرام'
		],
		[
			'key' => 'contact_us_tab',
			'label' => __( 'Contact Us', 'artist' ),
			'name' => 'contact_us_tab',
			'type' => 'tab',
		],
		[
			'key' => 'contact_us_section_title',
			'label' => __( 'Section Title', 'artist' ),
			'name' => 'contact_us_section_title',
			'default_value' => 'پاسخ سوال خود را پیدا نکردید؟',
			'type' => 'text',
		],
		[
			'key' => 'contact_us_section_subtitle',
			'label' => __( 'Section SubTitle', 'artist' ),
			'name' => 'contact_us_section_subtitle',
			'default_value' => 'شما می‌توانید با پر کردن فرم تماس و پرسیدن سوال خود با ما در تماس باشید',
			'type' => 'text',
		],
		[
			'key' => 'contact_us_section_button_text',
			'label' => __( 'Button Text', 'artist' ),
			'name' => 'contact_us_section_button_text',
			'default_value' => 'فرم تماس با ما',
			'type' => 'text',
		],
		[
			'key' => 'pages_tab',
			'label' => __( 'Page Definitions', 'artist' ),
			'name' => 'pages_tab',
			'type' => 'tab',
		],
		[
			'key' => '_page_about',
			'label' => __( 'About Page', 'artist' ),
			'name' => '_page_about',
			'type' => 'post_object',
			'post_type' => 'page',
		],
		[
			'key' => '_page_blog',
			'label' => __( 'Blog Page', 'artist' ),
			'name' => '_page_blog',
			'type' => 'post_object',
			'post_type' => 'page',
		],
		[
			'key' => '_page_faq',
			'label' => __( 'FAQ', 'artist' ),
			'name' => '_page_faq',
			'type' => 'post_object',
			'post_type' => 'page',
		],
		[
			'key' => '_page_support',
			'label' => __( 'Support', 'artist' ),
			'name' => '_page_support',
			'type' => 'post_object',
			'post_type' => 'page',
		],
		[
			'key' => 'security_tab',
			'label' => __( 'Security', 'artist' ),
			'name' => 'security_tab',
			'type' => 'tab',
		],
		[
			'key' => 'captcha_sitekey',
			'label' => __( 'Google Captcha SiteKey', 'artist' ),
			'name' => 'captcha_sitekey',
			'type' => 'text',
		],
		[
			'key' => 'captcha_secretkey',
			'label' => __( 'Google Captcha SecretKey', 'artist' ),
			'name' => 'captcha_secretkey',
			'type' => 'text',
		],
	],
	'location' => [
		[
			[
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			],
		],
	],
	'style' => 'seamless',
];